### ISSUE TITLE
DebugWeb - Help Getting it running

### ISSUE THREAD

**Issue by larrywelch** [scottdurow/SparkleXrm#137]
I love the idea of the DebugWeb project as I'm getting ready to travel tomorrow and would like to work on the plane.  The ReadMe.txt file indicates that the CRM Server details needs to be set in the Client....  Can you provide more specifics on the settings?  I changed the following as this is what's set in the project properties->Web Project URL.  However, I am not able to load MultiEntitySearch.htm from the sample project.  

Any help will be appreciated!

**Comment by scottdurow** [comment]
The DebugWeb is actually something I don't use anymore because I've found it more productive to use Fiddler and debug inside Dynamics it's self  [without actually deploying the webresources](http://www.sparklexrm.com/s/Tutorials/SetUpNewProject.html)  The issue being authentication is difficult outside of Dynamics.

**Comment by scottdurow** [comment]
Hope your trip went well 👍
