### ISSUE TITLE
ViewModel, IsBusy, Form, Webresource

### ISSUE THREAD

**Issue by larrywelch** [scottdurow/SparkleXrm#144]
I know the title is a mouth full :).  I'm using the ClientHooks project to host a View/ViewModel type solution.  I really only need the typical ClientHooks type project but as I got going I decided I liked the IsBusy feature of a SparkleXrm ViewModel.  I decided to create a simple View/ViewModel within the ClientHooks to see if I could make the IsBusy feature work.  I wired it all up in about 10 minutes and added it to my form as a webresource.  I see the IsBusy indicator, but only at the end of my processing loop.  The processing starts when a button is pushed, loops through creating new related entities, and then reports a completed message.  

Is there a trick to making this happen in a form?  I've not had any issues making it work in a Dashboard.

**Comment by scottdurow** [comment]
The View/ViewModel uses the Observable bindings of Knockout and isn't designed to be used in a ClientHooks. This is because the data binding observables are designed primarily for HTML dom binding which you'd never be doing in a ClientHooks - also the only libraries that are registered in ClientHooks project should be the mscorlib_crm.js and SparkleXrm.js

It sounds like you need some kind of async progress callback mechansim for form events? 

Hope that makes senses.
