### ISSUE TITLE
Predefined Type '' is not defined or imported

### ISSUE THREAD

**Issue by interfacemirror** [scottdurow/SparkleXrm#226]
Hello Scott,

After including Sparkle package in my solution from Nuget, I get so many errors saying "Predefined Type '' is not defined or imported". It seems that after the import it does something with the solution and package and causing the error.

I am using Dynamics 365 SDK version 9.0.0.7 and VS 2017.

**Comment by janis-veinbergs** [comment]
Hello @scottdurow. Same with me. I see you have committed vsix for Script# for VS2017 which I have installed. However build fails because of these errors.

Looking at references I see that mscorlib has yellow exclamation mark there and it says Version 0.0.0.0 within properties. I suspect it cannot find Script# DLL. However it IS located here: `SparkleXrmTemplateVS2016DeveloperToolkit365\packages\ScriptSharp.0.7.5.1\tools\mscorlib.dll`

I'v verified that ClientUI.csproj has this line: `<Import Project="..\packages\ScriptSharp.0.7.5.1\tools\ScriptSharp.targets" Condition="Exists('..\packages\ScriptSharp.0.7.5.1\tools\ScriptSharp.targets')" />` and that .targets file is identical to some old VS2012 project which works.

I have this in msbuild log:
```
1>  Dependency "mscorlib, Version=0.7.0.0, Culture=neutral, PublicKeyToken=8fc0e3af5abcb6c4".
1>      Could not resolve this reference. Could not locate the assembly "mscorlib, Version=0.7.0.0, Culture=neutral, PublicKeyToken=8fc0e3af5abcb6c4". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
```

And i **DO NOT** have this in log file (compared to sucessfull build on other project in VS2012):
```
1>Target "BuildScript" in file "C:\Users\JanisV\Development\Source\CRM\DEAC.CRM.CRM\DEAC.CRM.ConnectionsUI\packages\ScriptSharp.0.7.5.1\tools\ScriptSharp.targets" from project "C:\Users\JanisV\Development\Source\CRM\DEAC.CRM.CRM\DEAC.CRM.ConnectionsUI\ClientUI\DEAC.CRM.ConnectionsUI.ClientUI.csproj" (target "Build" depends on it):
1>Using "ScriptCompilerTask" task from assembly "C:\Users\JanisV\Development\Source\CRM\DEAC.CRM.CRM\DEAC.CRM.ConnectionsUI\packages\ScriptSharp.0.7.5.1\tools\ScriptSharp.Build.dll".
```

The ScriptSharp.targets probably get parsed, because I see:
```
1>BuildDependsOn = 
1>            RestorePackages;
1>            
1>      EntityDeploy;
1>      
1>      BeforeBuild;
1>      CoreBuild;
1>      AfterBuild
1>    
1>    ;
1>        ;BuildScript

```
Regarding SparkleXrm\NuGet\ScriptSharp.vsix - what should it do when I install it?I see v7.6.0 under `%localappdata%\Microsoft\VisualStudio\15.0_9d3398e1\Extensions\bpy2lfef.tnj\Packages\ScriptSharp.0.7.6.0.nupkg` but this package doesn't appear. Added this path manually to NuGet packages, updated ScriptSharp to 0.7.6.0 - still same issue.

Tried removing/adding mscorlib manually to references and it says: `A reference to ...\mscorlib.dll could not be added. This component is already automatically referenced by the build system.`. Except it cannot find mscorlib.dll during the build :(

**Comment by scottdurow** [comment]
Yeah - you're right - we need to update the template for this. Any takers?

**Comment by janis-veinbergs** [comment]
Thanks for quick responses. Looks like you had sorted that out.
Would you explain please what is the correct way to kickstart project using VS2017? Because tutorials seems outdated and looks like you actually had this fix, but within different project. Was it just to build SparkleXRM but not SparkleXRM solutions?

Maybe other templates also need including these directives?
