### ISSUE TITLE
Message: Message property name 'Target' is not valid on message DeliverIncoming

### ISSUE THREAD

**Issue by clc136** [scottdurow/SparkleXrm#285]
Hi Scott,
Just started using the spkl taskrunner package and pretty happy thanks :-)
Unfortunately I'm seeing a couple of issues:
Deploying plugins : Message: Message property name 'Target' is not valid on message DeliverIncoming
Deploying CWAs: Duplicate workflow activity names (due to a Test DLL built in the path folder) 
Thought to build/debug in my local repo but using VS2015 having package problems with QualityTesting...
Any insights gratefully received.
BTW, I am using using ILMerge due to substantial shared IoC code rather than other dependencies.
Thanks, Chris

**Comment by mikeread2018** [comment]
Hi Scott, This is due to the DeliverPromote, DeliverIncoming and Send messages are missing from the "switch" in PuliginRegistration.cs LN 486, See reference https://docs.microsoft.com/en-us/previous-versions/dynamics-crm4/developers-guide/cc154526(v%3Dmsdn.10).

I've fixed here, just need to pull and fix with your branch

**Comment by scottdurow** [comment]
Thanks Mike - if you could submit a PR into the https://github.com/scottdurow/SparkleXrm/tree/spkl_dev branch that would be awesome.

**Comment by ryanmichaeljames** [comment]
Hey@scottdurow. Please see pull request #301. I've added support for the `EmailId` message property name.

**Comment by scottdurow** [comment]
This is released as https://www.nuget.org/packages/spkl/1.0.370
