### ISSUE TITLE
Thought on replacing CrmSvcUtil with Power Apps CLI in `spkl`?

### ISSUE THREAD

**Issue by skfd** [scottdurow/SparkleXrm#449]
I would like to discuss replacing CrmSvcUtil with Power Apps CLI. Is there any benefits, are there any drawbacks?

Thank you

**Comment by scottdurow** [comment]
Do you mean replacing use of SolutionPackager? I've not seen support for early bound types in the PAC?
If so, the PAC uses SolutionPackager under the hood - so wouldn't see much difference other than the deployment mechanism. That said - I can see a time when PAC would replace spkl's pack/unpack commands since they are essentially doing the same.

**Comment by skfd** [comment]
No on-premise support in `pac` as I've learned! `spkl` wins!
