### ISSUE TITLE
 Subgrid validation message issue

### ISSUE THREAD

**Issue by tinunelson** [scottdurow/SparkleXrm#79]
Hi Scott,

There is an issue with the subgrid validation message in a subgrid which I developed using Sparkle. The validation message is coming on top of the validated field. Please see the attached screenshot. Because of this, the users are not able to click on the field and correct the value. This is happening only on the first row as there is no space on top to show the message. Is there a way to make the error message appear above the field?

![error subgrid](https://cloud.githubusercontent.com/assets/15125912/11453679/34ced68c-963a-11e5-8016-d90f6b8d13cc.jpg)

Thanks,
Tinu Nelson

**Comment by scottdurow** [comment]
The validation popup uses jQuery position with collision set to 'fit' - see https://github.com/scottdurow/SparkleXrm/blob/master/SparkleXrmSource/SparkleXrmUI/GridEditor/GridDataViewBinder.cs#L483
This normally works as long as your validation fits on a single line - but in your case it is wrapping to two lines. 
Perhaps this behaviour could be configurable to use 'none none' rather than 'fit fit'? What do you think?

**Comment by tinunelson** [comment]
Thanks for the replay.. I tried it. It is working perfectly..

![capture](https://cloud.githubusercontent.com/assets/15125912/11475609/4c724484-97a4-11e5-8d5c-4632402719db.JPG)

**Comment by scottdurow** [comment]
How would you like this moving into the next release - a switch?

**Comment by tinunelson** [comment]
Yes.It will be great if you could make it configurable in the next release.
