### ISSUE TITLE
Building the template

### ISSUE THREAD

**Issue by mbeauchamp7** [scottdurow/SparkleXrm#81]
Hi,

I really appreciate your initiative to build this magnificent library and I'm working on starting to use it!
As I was following your tutorial to get started with the project template, I got this error when I was building and I can't figure out how to fix it...

Error	26	The command "
xcopy "C:\Clients Dynamics CRM\DEV\GS_Sparkle\SparkleXrmCrmPackage\CrmPackage\WebResources\js\ClientUI.debug.js" "C:\Clients Dynamics CRM\DEV\GS_Sparkle\SparkleXrmCrmPackage\CrmPackage\WebResources/js/ClientUI.js" /y /i /o
xcopy "C:\Clients Dynamics CRM\DEV\GS_Sparkle\SparkleXrmCrmPackage\CrmPackage\WebResources\js\ClientHooks.debug.js" "C:\Clients Dynamics CRM\DEV\GS_Sparkle\SparkleXrmCrmPackage\CrmPackage\WebResources/js/ClientHooks.js" /y /i /o

" exited with code 4.	C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets	1063	6	CrmPackage

Thank you for your time!

**Comment by scottdurow** [comment]
Try building each project individually first, then build the solution. Also - check that there are no strange permissions on your folders.

**Comment by tinunelson** [comment]
Also, please try running the visual studio as administrator....

**Comment by mbeauchamp7** [comment]
Running as administrator worked! Thanks tinunelson

**Comment by pierrejoubert** [comment]
Hi, 

I know this an old issue/question, but I thought I would raise this again.  Running as administrator is not always a solution in corporate environments - builds with no issue on my personal Win10 machine but at work it is a different story.

I found this is due to the "/o" switch.  Removing the switch resolves the build issue without the need for "Run as Administrator".  The security on Vista and up is what is causing this, maybe look at using robocopy instead as xcopy has been depreciated.  

Its a small annoyance rather than an issue.  😃 

Thanks for the fantastic solutions.
