### ISSUE TITLE
Question about shared validation logic client side and plugin (server-side)

### ISSUE THREAD

**Issue by janis-veinbergs** [scottdurow/SparkleXrm#96]
Hello.

From [sparklexrm.com](http://www.sparklexrm.com/s/features.html) I read that:
> Sparkle XRM is designed to enable you to write C# code and compile to JavaScript and Plugin Code at the same time. Write your validation logic once and use it when your users enter data into standard CRM forms, custom Webresources or called from Plugins when updating via Bulk Upload or Bulk Updates.

@ScottColson, Could you please provide guidance on how do we do it, that is:

- In which project do I put my shared logic?
- Should I still use the Script Class Item template when writing this shared code?
- Can we also use SparkleXrm validation framework there?
- Anything else we should know?

SparkleXrm looks a well-written framework, however really lacks documentation.

**Comment by scottdurow** [comment]
You can put your shared code in either the server or the client project and then include to the other using [link ](https://support.microsoft.com/en-us/kb/306234)rather than add in Visual Studio.

You can then use conditional code to include a different set of includes if need be:

```
#if SCRIPTSHARP

#else

#endif
```

Using this same technique you can share constant definitions or code that can be compiled both server and client - simple business logic and fetchxml query generation functions work well.

You can't use the Validation Data Binder at this time on the Server but that sounds like an interesting idea.

We are always looking for [help with documentation.](https://github.com/scottdurow/SparkleXrm/wiki/How-sparkleXRM-works-&-the-benefit-it-brings)
